/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHealthDiagnosticsRouteImport } from './routes/api/public/health.diagnostics'
import { Route as ApiPublicHealthAiRouteImport } from './routes/api/public/health.ai'

const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthDiagnosticsRoute =
  ApiPublicHealthDiagnosticsRouteImport.update({
    id: '/api/public/health/diagnostics',
    path: '/api/public/health/diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthAiRoute = ApiPublicHealthAiRouteImport.update({
  id: '/api/public/health/ai',
  path: '/api/public/health/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classroom': typeof ClassroomRoute
  '/debug': typeof DebugRoute
  '/api/public/health/ai': typeof ApiPublicHealthAiRoute
  '/api/public/health/diagnostics': typeof ApiPublicHealthDiagnosticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classroom': typeof ClassroomRoute
  '/debug': typeof DebugRoute
  '/api/public/health/ai': typeof ApiPublicHealthAiRoute
  '/api/public/health/diagnostics': typeof ApiPublicHealthDiagnosticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classroom': typeof ClassroomRoute
  '/debug': typeof DebugRoute
  '/api/public/health/ai': typeof ApiPublicHealthAiRoute
  '/api/public/health/diagnostics': typeof ApiPublicHealthDiagnosticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classroom'
    | '/debug'
    | '/api/public/health/ai'
    | '/api/public/health/diagnostics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classroom'
    | '/debug'
    | '/api/public/health/ai'
    | '/api/public/health/diagnostics'
  id:
    | '__root__'
    | '/'
    | '/classroom'
    | '/debug'
    | '/api/public/health/ai'
    | '/api/public/health/diagnostics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassroomRoute: typeof ClassroomRoute
  DebugRoute: typeof DebugRoute
  ApiPublicHealthAiRoute: typeof ApiPublicHealthAiRoute
  ApiPublicHealthDiagnosticsRoute: typeof ApiPublicHealthDiagnosticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/diagnostics': {
      id: '/api/public/health/diagnostics'
      path: '/api/public/health/diagnostics'
      fullPath: '/api/public/health/diagnostics'
      preLoaderRoute: typeof ApiPublicHealthDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/ai': {
      id: '/api/public/health/ai'
      path: '/api/public/health/ai'
      fullPath: '/api/public/health/ai'
      preLoaderRoute: typeof ApiPublicHealthAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassroomRoute: ClassroomRoute,
  DebugRoute: DebugRoute,
  ApiPublicHealthAiRoute: ApiPublicHealthAiRoute,
  ApiPublicHealthDiagnosticsRoute: ApiPublicHealthDiagnosticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
